num1 = input("Enter the frist number ")
num2 = input("Enter the second number ")
num1 =float(num1)
num2 =float(num2)
Sum = str(num1+num2)
sub = str(num1-num2)
mul = str(num1*num2)
div = str(num1/num2)

print ("Sum is : " +Sum)
print ("Sub is : "+sub )
print ("Mul is : "+mul )
print ("div is : "+div )